slug: :mikutter_pictcollect
depends:
  mikutter: '3.3'
  plugin:
  - gtk
  - command
  - settings
  - openimg
version: '0.2'
author: Akkiesoft
name: mikutter_pictcollect
description: ツイートの画像を特定の場所に保存するプラグイン
